CREATE TABLE hyper_telemetries (
    internal_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(), 
    "device_id"     INTEGER             NOT NULL,
	"time"		INTEGER				NOT NULL,
	"x"          	DOUBLE PRECISION    NOT NULL,
	"y"          	DOUBLE PRECISION    NOT NULL,
	"z"          	DOUBLE PRECISION    NOT NULL,
	"gx"         	DOUBLE PRECISION    NOT NULL,
	"gy"         	DOUBLE PRECISION    NOT NULL,
	"gz"         	DOUBLE PRECISION    NOT NULL,
	"total"		DOUBLE PRECISION 	NOT NULL,
	"roll"        DOUBLE PRECISION    NOT NULL,
	"pitch"       DOUBLE PRECISION    NOT NULL,
	"yaw"         DOUBLE PRECISION    NOT NULL,
	"status"		VARCHAR NOT NULL,
	-- "latitude"      DECIMAL             NOT NULL,
	-- "longitude"     DECIMAL             NOT NULL,
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMPTZ         NULL
) WITH (
    tsdb.hypertable
);