CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE pengawas_role_enum AS ENUM
(
	'Admin',
	'Pengawas'
);

CREATE TABLE pengawas
(
    internal_id     INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID            NOT NULL DEFAULT gen_random_uuid(),
    nama            VARCHAR(100)    NOT NULL,
    pass_hash       VARCHAR(255)    NOT NULL,
    role            pengawas_role_enum       NOT NULL DEFAULT 'Pengawas',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMPTZ     NULL,
    CONSTRAINT      pengawas_public_id_unique UNIQUE(public_id)
);
