CREATE TABLE devices
(
    internal_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    pekerja_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT      device_public_id_unique  UNIQUE(public_id),
    CONSTRAINT      device_fk_worker   FOREIGN KEY (pekerja_id) REFERENCES pekerjas(internal_id) ON DELETE SET NULL
);
